version: '3'
services:

  demo_db:
    container_name: "demo_db"
    image: "postgres"
    ports:
      - "5433:5432"
    env_file:
      - .env
      - .env.local
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down

  demo_api:
    container_name: "demo_api"
    build: .
    command: ./demo-store-api
    depends_on:
      - demo_db
    ports:
      - "8081:8080"
    env_file:
      - .env
      - .env.local

  # demo_projector:
  #   container_name: "demo_projector"
  #   build: .
  #   command: ./demo-store-projector
  #   depends_on:
  #     - demo_db
  #   env_file:
  #     - .env
  #     - .env.local

volumes:
  database-data:
